### ISSUE TITLE
PS - Construcción de algoritmo en paralelo

### ISSUE THREAD

**Issue by anabco** [lauragmz/proyecto-final-mno2020#25]

**Comment by lauragmz** [comment]
- [ ] Se añade un primer ejemplo de paralelizar 2 tareas de particle swarm utilizando dask.delayed [notebook](https://github.com/lauragmz/proyecto-final-mno2020/blob/master/notebooks/Ejemplo_Paralelo_ParticleSwarm.ipynb)

**Comment by lauragmz** [comment]
- [ ] Se añade un segundo ejemplo de paralelizar 30 tareas de particle swarm, diviéndolas en 4 cores.
